# Generated by Django 4.1.3 on 2023-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='notarial',
            field=models.BooleanField(default=False),
        ),
    ]
