# Generated by Django 5.0.1 on 2024-01-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='producto',
        ),
    ]
