# Generated by Django 5.0.1 on 2024-01-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_entrega_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
