# Generated by Django 4.1.3 on 2023-06-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='permisos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rutas',
        ),
    ]
