# Generated by Django 4.1.3 on 2022-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='orden',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
