# Generated by Django 5.0.1 on 2024-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tiempo',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
