# Generated by Django 4.1.3 on 2023-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enPreparacion',
            field=models.BooleanField(default=False),
        ),
    ]
