# Generated by Django 4.1.3 on 2022-11-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='completado',
            field=models.BooleanField(default=True),
        ),
    ]
