# Generated by Django 4.1.3 on 2023-06-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=11)),
                ('escribano', models.BooleanField(default=False)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
