# Generated by Django 4.1.3 on 2022-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
