# Generated by Django 4.1.3 on 2023-01-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_escribano_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
