# Generated by Django 5.0.1 on 2024-01-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='sector_id',
            new_name='sector',
        ),
    ]
