# Generated by Django 4.1.3 on 2023-05-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectors',
            old_name='step_id',
            new_name='step',
        ),
    ]
