# Generated by Django 4.1.3 on 2023-05-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_step_id_sectors_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectors',
            old_name='step',
            new_name='step_id',
        ),
    ]
