# Generated by Django 4.1.3 on 2023-05-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_rename_step_id_sectors_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='step',
            new_name='step_number',
        ),
    ]
