# Generated by Django 4.1.3 on 2023-05-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_rename_step_steps_step_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectors',
            old_name='step',
            new_name='step_id',
        ),
    ]
