# Generated by Django 4.1.3 on 2023-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_rename_step_sectors_step_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='tiempo',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
